version: '3.8'

services:
  init:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: [ "/bin/sh", "-c", "scripts/create-env-file.sh" ]
  n8n:
    build: .
    container_name: jira_issues_n8n
    depends_on:
      - init
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "admin"
      N8N_BASIC_AUTH_PASSWORD: "adminpassword"
      WEBHOOK_TUNNEL_URL: "http://localhost:5678"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_PUBLIC_API_DISABLED: "true"
      N8N_RUNNERS_ENABLED: "true"
      GENERIC_TIMEZONE: "UTC"
      N8N_HOST: "localhost"
      N8N_PORT: "5678"
      N8N_CUSTOM_EXTENSIONS: "/home/node/.n8n/custom/node_modules/custom_nodes"
    volumes:
      - n8n_data:/home/node/.n8n
      - .env:/home/node/.env
      - ./workflows:/home/node/.n8n/workflows
      - ./credentials:/home/node/.n8n/credentials
      - ./custom_nodes:/home/node/.n8n/custom/node_modules/custom_nodes
    ports:
      - "5678:5678"

  mongodb:
    image: mongo:latest
    depends_on:
      - n8n
    container_name: jira_issues_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MONGO_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${MONGO_PASSWORD}"
      MONGO_INITDB_DATABASE: "${MONGO_DB}"
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      n8n_network:
        ipv4_address: 192.168.1.101

  mariadb:
    image: mariadb:latest
    depends_on:
      - n8n
    container_name: jira_issues-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      n8n_network:
        ipv4_address: 192.168.1.12

volumes:
  n8n_data:
  mongo_data:
  mariadb_data:

networks:
  n8n_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24